### ISSUE TITLE
Improve GoDocs for all go libraries

### ISSUE THREAD

**Issue by afiune** [chef/go-libs#10]
### Describe the Enhancement:
Improve the documentation for all the go libraries in this repository following the 
standards from [GoDoc](https://blog.golang.org/godoc-documenting-go-code).

**Comment by tyler-ball** [comment]
We also get free 'hosting' (it's just interpreting the code from github, but we don't have to do anything :partychef:) - https://godoc.org/github.com/chef/go-libs/config

**Comment by afiune** [comment]
Closed by https://github.com/chef/go-libs/pull/17
